// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLusterSchedulerStatus) DeepCopyInto(out *CLusterSchedulerStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLusterSchedulerStatus.
func (in *CLusterSchedulerStatus) DeepCopy() *CLusterSchedulerStatus {
	if in == nil {
		return nil
	}
	out := new(CLusterSchedulerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAccessSpec) DeepCopyInto(out *ClusterAccessSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAccessSpec.
func (in *ClusterAccessSpec) DeepCopy() *ClusterAccessSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterApiServerSpec) DeepCopyInto(out *ClusterApiServerSpec) {
	*out = *in
	out.ImageBase = in.ImageBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterApiServerSpec.
func (in *ClusterApiServerSpec) DeepCopy() *ClusterApiServerSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterApiServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterApiServerStatus) DeepCopyInto(out *ClusterApiServerStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterApiServerStatus.
func (in *ClusterApiServerStatus) DeepCopy() *ClusterApiServerStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterApiServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterClientSpec) DeepCopyInto(out *ClusterClientSpec) {
	*out = *in
	out.ImageBase = in.ImageBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterClientSpec.
func (in *ClusterClientSpec) DeepCopy() *ClusterClientSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterClientStatus) DeepCopyInto(out *ClusterClientStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterClientStatus.
func (in *ClusterClientStatus) DeepCopy() *ClusterClientStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterControllerManagerSpec) DeepCopyInto(out *ClusterControllerManagerSpec) {
	*out = *in
	out.ImageBase = in.ImageBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterControllerManagerSpec.
func (in *ClusterControllerManagerSpec) DeepCopy() *ClusterControllerManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterControllerManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterControllerManagerStatus) DeepCopyInto(out *ClusterControllerManagerStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterControllerManagerStatus.
func (in *ClusterControllerManagerStatus) DeepCopy() *ClusterControllerManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterControllerManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterEtcdSpec) DeepCopyInto(out *ClusterEtcdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterEtcdSpec.
func (in *ClusterEtcdSpec) DeepCopy() *ClusterEtcdSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterEtcdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterEtcdStatus) DeepCopyInto(out *ClusterEtcdStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterEtcdStatus.
func (in *ClusterEtcdStatus) DeepCopy() *ClusterEtcdStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterEtcdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInitSpec) DeepCopyInto(out *ClusterInitSpec) {
	*out = *in
	out.ImageBase = in.ImageBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInitSpec.
func (in *ClusterInitSpec) DeepCopy() *ClusterInitSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterInitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInitStatus) DeepCopyInto(out *ClusterInitStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInitStatus.
func (in *ClusterInitStatus) DeepCopy() *ClusterInitStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterInitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKubeProxySpec) DeepCopyInto(out *ClusterKubeProxySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKubeProxySpec.
func (in *ClusterKubeProxySpec) DeepCopy() *ClusterKubeProxySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterKubeProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterKubeletSpec) DeepCopyInto(out *ClusterKubeletSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterKubeletSpec.
func (in *ClusterKubeletSpec) DeepCopy() *ClusterKubeletSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterKubeletSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlugin) DeepCopyInto(out *ClusterPlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlugin.
func (in *ClusterPlugin) DeepCopy() *ClusterPlugin {
	if in == nil {
		return nil
	}
	out := new(ClusterPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPluginList) DeepCopyInto(out *ClusterPluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPluginList.
func (in *ClusterPluginList) DeepCopy() *ClusterPluginList {
	if in == nil {
		return nil
	}
	out := new(ClusterPluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPluginPodStatus) DeepCopyInto(out *ClusterPluginPodStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPluginPodStatus.
func (in *ClusterPluginPodStatus) DeepCopy() *ClusterPluginPodStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPluginPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPluginSpec) DeepCopyInto(out *ClusterPluginSpec) {
	*out = *in
	in.Install.DeepCopyInto(&out.Install)
	in.Uninstall.DeepCopyInto(&out.Uninstall)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPluginSpec.
func (in *ClusterPluginSpec) DeepCopy() *ClusterPluginSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPluginStatus) DeepCopyInto(out *ClusterPluginStatus) {
	*out = *in
	in.InstallStatus.DeepCopyInto(&out.InstallStatus)
	in.UninstallStatus.DeepCopyInto(&out.UninstallStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPluginStatus.
func (in *ClusterPluginStatus) DeepCopy() *ClusterPluginStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPostInstallStatus) DeepCopyInto(out *ClusterPostInstallStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPostInstallStatus.
func (in *ClusterPostInstallStatus) DeepCopy() *ClusterPostInstallStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPostInstallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSchedulerSpec) DeepCopyInto(out *ClusterSchedulerSpec) {
	*out = *in
	out.ImageBase = in.ImageBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSchedulerSpec.
func (in *ClusterSchedulerSpec) DeepCopy() *ClusterSchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	if in.RegistryMirrors != nil {
		in, out := &in.RegistryMirrors, &out.RegistryMirrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.AccessSpec = in.AccessSpec
	out.InitSpec = in.InitSpec
	out.EtcdSpec = in.EtcdSpec
	out.ApiServerSpec = in.ApiServerSpec
	out.ControllerManagerSpec = in.ControllerManagerSpec
	out.SchedulerSpec = in.SchedulerSpec
	out.ClientSpec = in.ClientSpec
	out.KubeletSpec = in.KubeletSpec
	out.KubeProxySpec = in.KubeProxySpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	in.Init.DeepCopyInto(&out.Init)
	in.Etcd.DeepCopyInto(&out.Etcd)
	in.ApiServer.DeepCopyInto(&out.ApiServer)
	in.ControllerManager.DeepCopyInto(&out.ControllerManager)
	in.Scheduler.DeepCopyInto(&out.Scheduler)
	in.Client.DeepCopyInto(&out.Client)
	in.PostInstall.DeepCopyInto(&out.PostInstall)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBase) DeepCopyInto(out *ImageBase) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBase.
func (in *ImageBase) DeepCopy() *ImageBase {
	if in == nil {
		return nil
	}
	out := new(ImageBase)
	in.DeepCopyInto(out)
	return out
}
