# permissions for end users to view clusterplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterplugin-viewer-role
rules:
- apiGroups:
  - cluster.kok.tanx
  resources:
  - clusterplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.kok.tanx
  resources:
  - clusterplugins/status
  verbs:
  - get
