
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cluster.kok.tanx
  resources:
  - clusterplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.kok.tanx
  resources:
  - clusterplugins/status
  verbs:
  - get
  - patch
  - update
