apiVersion: cluster.kok.tanx/v1
kind: ClusterPlugin
metadata:
  name: test
  namespace: test
spec:
  clusterName: test
  install:
    containers:
      - command:
          - 'cat'
          - '/root/.kube/config'
        image: ubuntu:latest
        name: test
  uninstall:
    containers:
      - command:
          - cat
          - /etc/cluster/config
        image: ubuntu:latest
        name: test
