apiVersion: cluster.kok.tanx/v1
kind: MultiClusterPlugin
metadata:
  name: test
  namespace: test
spec:
  clusters:
    - test
  install:
    containers:
      - command:
          - 'cat'
          - '/etc/cluster/test/config'
        image: ubuntu:latest
        name: test
  uninstall:
    containers:
      - command:
          - 'cat'
          - '/etc/cluster/test/config'
        image: ubuntu:latest
        name: test

