apiVersion: cluster.kok.tanx/v1
kind: ClusterPlugin
metadata:
  name: test
  namespace: test
spec:
  cluster_name: test
  install:
    containers:
      - command:
          - date
        image: ubuntu:latest
        name: test
  uninstall:
    containers:
      - command:
          - date
        image: ubuntu:latest
        name: test
