FROM ccr.ccs.tencentyun.com/k8sonk8s/proxy:ubuntu-20.04-arm
WORKDIR /home
RUN apt update && apt install wget -y
COPY cfssl /usr/bin/
COPY cfssljson /usr/bin/
COPY cfssl-certinfo /usr/bin/
RUN chmod +x /usr/bin/cfssl*
COPY kubectl /usr/bin/kubectl
ADD init.sh /home/init.sh
RUN chmod a+x /home/init.sh
CMD ['sh /home/init.sh']